services:
  - type: web
    name: todo-app
    env: node
    plan: free
    buildCommand: |
      npm --prefix frontend install
      npm --prefix frontend run build
      npm --prefix backend install
    startCommand: "npm --prefix backend start"
    envVars:
      - key: PORT
        value: "5001"
      - key: NODE_ENV
        value: "production"
      - key: CORS_ORIGIN
        value: "https://todo-app-1112.onrender.com"
