services:
  - type: web
    name: todo-app-1112
    runtime: node
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_CONNECTIONSTRING
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_PROVIDER
        value: sendgrid
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://todo-app-kaito20.vercel.app